version: '3.8'

services:
  user-service:
    image: ghcr.io/your-username/user-service:latest
    environment:
      - DB_HOST=postgres-production  
      - ENVIRONMENT=production
    ports:
      - "8090:8090"
    deploy:
      replicas: 2

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=userdb_production
