global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['103.125.216.110:8095']
    metrics_path: /metrics
    scrape_interval: 10s
