global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8090']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['103.125.216.110:9090']
    scrape_interval: 30s
