version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-prod
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: production123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    image: golang:1.21-alpine
    container_name: user-service-prod
    working_dir: /app
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=userdb
      - DB_USER=postgres
      - DB_PASSWORD=production123
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: >
      sh -c "
        go mod download &&
        go run cmd/api/main.go
      "
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
