#!/bin/bash
echo "🚀 DevOps Project Successfully Deployed to GitHub!"
echo "=================================================="
echo "🌐 Repository: https://github.com/Evgen242/user-service-devops-production"
echo "🔧 CI/CD:      https://github.com/Evgen242/user-service-devops-production/actions"
echo ""
echo "🐳 Quick Start:"
echo "  docker-compose -f docker-compose-corrected.yml up -d"
echo "  curl http://localhost:8090/health"
echo "  # Grafana: http://localhost:3000 (admin/admin123)"
echo "  # Prometheus: http://localhost:9090"
echo ""
echo "🏆 Project Features:"
echo "  ✅ Go microservice + PostgreSQL"
echo "  ✅ Docker + Docker Compose"
echo "  ✅ Prometheus + Grafana monitoring"
echo "  ✅ GitHub Actions CI/CD"
echo "  ✅ Security scanning"
echo "  ✅ Production ready configuration"
